main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import main_page, VacanciesListView, VacanciesDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', main_page, name='main_page'),
    path('vacancies/', VacanciesListView.as_view(), name='vacancies_list'),
    path('vacancies/<int:pk>/', VacanciesDetailView.as_view(), name='vacancy_detail'),
]

parser_hh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='parser_pages')),
]

main/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Vacancies(models.Model):
    id_vacancy = models.PositiveIntegerField(unique=True, verbose_name='ID вакансии')
    name_company = models.CharField(max_length=127, verbose_name='Название компании')
    name_vacancy = models.CharField(max_length=127, verbose_name='Название вакансии')
    adress = models.CharField(max_length=255, **NULLABLE, verbose_name='Адрес')
    url = models.URLField(verbose_name='Ссылка на вакансию')
    salary_from = models.PositiveIntegerField(**NULLABLE, verbose_name='Зарплата от')
    salary_to = models.PositiveIntegerField(**NULLABLE, verbose_name='Зарплата до')
    requirement = models.TextField(max_length=1024, verbose_name='Требования')
    responsibiliti = models.TextField(max_length=1023, **NULLABLE, verbose_name='Ответственность')
    date_created = models.DateTimeField(verbose_name='Дата публикации')
    view = models.BooleanField(default=False, verbose_name='Признак просмотра')

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ['-date_created']

    def __str__(self):
        return f'{self.name_vacancy}, {self.salary_from}, {self.salary_to}'


# class Company(models.Model):
#     id_company = models.PositiveIntegerField(unique=True, verbose_name='ID вакансии')
#     name_company = models.CharField(max_length=127, verbose_name='Название компании')
#     url = models.URLField(verbose_name='Ссылка на компанию')
#     address = models.CharField(max_length=255, **NULLABLE, verbose_name='Адрес')
#
#     class Meta:
#         verbose_name = 'Компания'
#         verbose_name_plural = 'Компании'
#         ordering = ['name_company']
#
#     def __str__(self):
#         return f'{self.name_company}, {self.url}, {self.address}'

main/forms.py
from django import forms


class RequestForm(forms.Form):
    keyword = forms.CharField(max_length=50, label='Слово для поиска')

main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView, DetailView

from main.forms import RequestForm
from main.models import Vacancies

from .utils.utils import requests


def main_page(request):
    request_form = RequestForm(request.POST)
    context = {'form': request_form}
    if request.method == 'POST':

        if request_form.is_valid():
            keyword = request_form.cleaned_data['keyword']
            requests(keyword)
            return HttpResponseRedirect(reverse('parser_pages:vacancies_list'))
        else:
            return render(request, 'main/main_page.html', context)
    else:
        return render(request, 'main/main_page.html', context)


class VacanciesListView(ListView):
    model = Vacancies
    queryset = Vacancies.objects.all()
    template_name = 'main/vacancies_list.html'
    paginate_by = 21


class VacanciesDetailView(DetailView):
    model = Vacancies
    template_name = 'main/vacancy_detail.html'

    def get_object(self, queryset=None):
        objects = super().get_object()
        objects.view = True
        objects.save()
        return objects

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" media="screen"/>

</head>
<body>


{% include 'main/inc/navbar.html' %}

{% block content %}

{% endblock %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'parser_pages:main_page' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05"
                aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'parser_pages:vacancies_list' %}">Вакансии</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form role="search">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/main_page.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3">

        </div>
        <div class="col-6">

            <form method="post" enctype="multipart/form-data">
                <p align="center">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" title="Нажми меня">
                </p>
            </form>

        </div>
        <div class="col-3">

        </div>
    </div>

{% endblock %}

main/templates/main/pagination/paginate.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}
            <span class="current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}.
            </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Следующая</a>
        {% endif %}
    </span>
</div>

main/templates/main/vacancies_list.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="container py-3">
        <header>
            <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
                <h1 class="display-4 fw-normal text-body-emphasis">Вакансии</h1>
                <p class="fs-5 text-body-secondary">Раздел находится в разработке.</p>
                <p class="fs-5 text-body-secondary">Пока можно видеть список спарсенных вакансий</p>
            </div>
        </header>

        <main>
            <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
                {% for object in object_list %}
                    <div class="col">
                        <div class="card mb-4 rounded-3 shadow-sm">
                            <div class="card-header py-3">
                                <h4 class="my-0 fw-normal">{{ object.name_company|truncatechars:20 }}</h4>
                            </div>
                            <div class="card-body">
                                <h3 class="card-title pricing-card-title">{{ object.name_vacancy|truncatechars:20 }}<small
                                        class="text-body-secondary fw-light"></small></h3>
                                <ul class="list-unstyled mt-3 mb-4">
                                    <li></li>
                                    <li>
                                            <strong>Зарплата:</strong>
                                       {% if object.salary_from and object.salary_to%}
                                            от {{ object.salary_from }} до {{ object.salary_to }}
                                        {% elif object.salary_from and object.salary_to == False%}
                                            от {{ object.salary_from }}
                                        {% elif object.salary_from == False and object.salary_to%}
                                            до {{ object.salary_to }}
                                        {% else %}
                                            Не указана
                                        {% endif %}
                                    </li>
                                    <li>{{ object.date_created }}</li>
                                </ul>
                                <a class="btn {% if object.view %}btn-primary{% else %}btn-success{% endif %}" href="{% url 'parser_pages:vacancy_detail' object.pk %}">Посмотреть</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
    </div>
        {% include 'main/pagination/paginate.html' with page=page_obj %}
{% endblock %}

main/templates/main/vacancy_detail.html
{% extends 'main/base.html' %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Вакансия</h1>
            <p class="fs-5 text-body-secondary">Раздел находится в разработке.</p>
            <p class="fs-5 text-body-secondary">Пока можно видеть список спарсенных вакансий</p>
        </div>
    </header>

    <main>
        <div class="row">
            <div class="col-4"></div>
            <div class="col-4">

                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">{{ object.name_company }}</h4>
                        </div>
                        <div class="card-body">
                            <h3 class="card-title pricing-card-title">{{ object.name_vacancy}}<small
                                    class="text-body-secondary fw-light"></small></h3>
                            <ul class="list-unstyled mt-3 mb-4">
                                <li><strong>Адрес</strong>: {% if object.adress %}{{ object.adress }}{% else %}Не указан{% endif %}</li>
                                <li>
                                            <strong>Зарплата:</strong>
                                       {% if object.salary_from and object.salary_to%}
                                            от {{ object.salary_from }} до {{ object.salary_to }}
                                        {% elif object.salary_from and object.salary_to == False%}
                                            от {{ object.salary_from }}
                                        {% elif object.salary_from == False and object.salary_to%}
                                            до {{ object.salary_to }}
                                        {% else %}
                                            Не указана
                                        {% endif %}
                                    </li>
                                <li><strong>Требования</strong>: {{ object.requirement|safe }}</li>
                                {% if object.responsibiliti %}
                                <li><strong>Задачи</strong>:{{ object.responsibiliti|safe }}</li>
                                {% endif %}
                                <li></li>
                                <li><a href="{{ object.url }}"></a></li>
                                {% if object.salary %}
                                <li>
                                {{ object.salary_from }}
                                {{ object.salary_to }}
                                {% endif %}
                                </li>
                                <li><strong>Ссылка</strong>: <a href="{{ object.url }}">{{ object.url }}</a></li>
                                <li><strong>Дата</strong>: {{ object.date_created }}</li>
                            </ul>
                            <a href="{% url 'parser_pages:vacancies_list' %}"
                                    class="w-100 btn btn-lg btn-primary">
                                Назад
                            </a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4"></div>
        </div>


    </main>

{% endblock %}